<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <!-- Неявные using отключены, чтобы System.Linq не подключался автоматически -->
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Pr3_TextAnalyzer</RootNamespace>
  </PropertyGroup>

</Project>
